<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" <?php language_attributes(); ?>>
	<head>
		<title><?php
			global $page, $paged;
			wp_title( '|', true, 'right' );
			bloginfo('name'); 
			$site_description = get_bloginfo( 'description', 'display' );
			if ( $site_description && ( is_home() || is_front_page() ) )
				echo " | $site_description";
			if ( $paged >= 2 || $page >= 2 )
				echo ' | ' . sprintf( __( 'Page %s'), max( $paged, $page ) );
		?></title>

		<meta http-equiv="Content-Type" content="<?php bloginfo('html_type'); ?>; charset=<?php bloginfo( 'charset' ); ?>" />
		<link rel="stylesheet" href="<?php bloginfo('stylesheet_url') ?>?ver=<?php $file = dirname(__FILE__) . '/style.css'; echo filemtime($file);?>" type="text/css" media="screen" />
		<!--[if IE 8]><link rel="stylesheet" href="<?php bloginfo('template_directory')?>/IE.css?ver=<?php $file = dirname(__FILE__) . '/IE8.css'; echo filemtime($file);?>" type="text/css" /><![endif]-->
		<!--[if IE 7]><link rel="stylesheet" href="<?php bloginfo('template_directory')?>/IE7.css?ver=<?php $file = dirname(__FILE__) . '/IE7.css'; echo filemtime($file);?>" type="text/css" /><![endif]-->
		<!--[if IE 6]><link rel="stylesheet" href="<?php bloginfo('template_directory')?>/IE6.css?ver=<?php $file = dirname(__FILE__) . '/IE6.css'; echo filemtime($file);?>" type="text/css" /><![endif]-->
		<script type='text/javascript' src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js"></script>
		<script type='text/javascript' src="<?php bloginfo('template_directory')?>/js/jquery.cycle.all.min.js"></script>
		<script type="text/javascript">
		$('#slides').cycle({
			fx: 'scrollLeft',
			sync: 1,
			fit: 1,
			timeout: 15000,
			speed:  750, 
			pager:  '#featurenav',
		});
		</script>
		<?php wp_head(); ?>
	</head>
	<body <?php body_class(); ?>>
		<div id="wrapper">
		<div id="header" class="clear">
			<span id="top"></span>
			<?php get_sidebar();?>
			<script type='text/javascript' src="<?php bloginfo('template_directory'); ?>/js/effects.js"></script>
			<script type="text/javascript">
			/* <![CDATA[ */
			jQuery(function(){
			jQuery("ul.menu").superfish({ 
			delay:       10000,
			speed:       250,
			autoArrows:  false,                           
			dropShadows: false 
			}); });
			//]]>
			</script>
		</div><!--header-->
			<div class="fcontent-box" >
				<div class="fcontent">
					<?php wp_nav_menu(  array( 'menu' => 'hsnu-menu', 'container' => '', 'menu_class' => 'clear menu fg-bt-menu' ) ); ?>
					<div id="slides">
					<?php	for ( $j = 1 ; $j <= 6 ; $j++ )
					{
						$out = get_option('ide2_fslide'.$j);
						// get_option() returns HTML 'escaped', so I'll strip out all backslashes
						// This might cause problems
						$out = stripslashes($out);
						echo $out;
					} ?>
					</div><!--slides-->
					<div id="featurenav">
						<!--Don't add anything, pager will be generated by the jQuery Cycle Plugin automatically-->
					</div>
					<script type='text/javascript' src="<?php bloginfo('template_directory')?>/js/effects.js"></script>
					<script type="text/javascript">
						/* <![CDATA[ */
						jQuery(function(){
						jQuery("ul.fg-bt-menu").superfish({ 
						delay:       3000,
						speed:       250,
						autoArrows:  false,                           
						dropShadows: false 
						 }); });
						/* ]]> */
					</script>
					<div class="mg-col text">
					<?php
					$out = get_option('ide2_fgcol1');
					$out = stripslashes($out);
					echo '<div class="fgcol">' . $out . '</div>';

					echo '<div class="fgcol">';
					do_action('get_newmsg', 10);
					echo '</div>';

					$out = get_option('ide2_fgcol2');
					$out = stripslashes($out);
					echo '<div class="fgcol">' . $out . '</div>';
					?>
					</div><!--mg-col-->
				</div><!--fcontent-->
			</div><!--fcontent-box-->
			<div id="fg-footer" class="clear text">
				<p><span id="fg-address">校址：106 台北市大安區信義路三段143號</span>
				<span>總機：(02) 2707-5215</span>
				<span>管理員信箱：<a href="mailto:<?php bloginfo('admin_email')?>"><?php bloginfo('admin_email')?></a></span>
				<span>&copy; <?php bloginfo('name'); ?></span></p>
			<a href="#top" class="mobile-text">top</a>
			</div><!--footer-->
		</div><!--wrapper-->
		<?php wp_footer(); ?>
	</body>
</html>
